[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"
description = "a cli text editor"

[dependencies]
crossterm = "0.28.1"
clap = { version = "4.5.23", features = ["derive"] }
ropey = "1.6.1"
